"""notification_db_foundation

Revision ID: 51ba577f6d32
Revises: 5942407a636b
Create Date: 2026-05-11 02:03:41.714122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ba577f6d32'
down_revision: Union[str, Sequence[str], None] = '5942407a636b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_severity', 'notifications', ['severity'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.drop_constraint(op.f('notifications_shipment_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_order_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_product_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'shipment_id')
    op.drop_column('notifications', 'order_id')
    op.drop_column('notifications', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('shipment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'unread'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_product_id_fkey'), 'notifications', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notifications_order_id_fkey'), 'notifications', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('notifications_shipment_id_fkey'), 'notifications', 'shipments', ['shipment_id'], ['id'])
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_severity', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'payload')
    # ### end Alembic commands ###
